### ISSUE TITLE
make zk 시 오류 

### ISSUE THREAD

**Issue by computerphilosopher** [jam2in/arcus-docker#3]
현재 make clean -> make zk 후 로그를 보면 다음과 같은 오류가 확인된다

```
JMX enabled by default
Using config: /arcus/zookeeper/bin/../conf/zoo.cfg
2020-11-11 06:32:00,238 [myid:] - INFO  [main:QuorumPeerConfig@101] - Reading configuration from: /arcus/zookeeper/bin/../conf/zoo.cfg
2020-11-11 06:32:00,253 [myid:] - INFO  [main:QuorumPeerConfig@334] - Defaulting to majority quorums
2020-11-11 06:32:00,260 [myid:1] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
2020-11-11 06:32:00,261 [myid:1] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 0
2020-11-11 06:32:00,261 [myid:1] - INFO  [main:DatadirCleanupManager@101] - Purge task is not scheduled.
2020-11-11 06:32:00,278 [myid:1] - INFO  [main:QuorumPeerMain@127] - Starting quorum peer
2020-11-11 06:32:00,303 [myid:1] - INFO  [main:NIOServerCnxnFactory@94] - binding to port 0.0.0.0/0.0.0.0:2181
2020-11-11 06:32:00,321 [myid:1] - INFO  [main:QuorumPeer@913] - tickTime set to 2000
2020-11-11 06:32:00,322 [myid:1] - INFO  [main:QuorumPeer@933] - minSessionTimeout set to 4000
2020-11-11 06:32:00,322 [myid:1] - INFO  [main:QuorumPeer@944] - maxSessionTimeout set to 200000
2020-11-11 06:32:00,322 [myid:1] - INFO  [main:QuorumPeer@959] - initLimit set to 10
2020-11-11 06:32:00,337 [myid:1] - INFO  [main:QuorumPeer@429] - currentEpoch not found! Creating with a reasonable default of 0. This should only happen when you are upgrading your installation
2020-11-11 06:32:00,340 [myid:1] - INFO  [main:QuorumPeer@444] - acceptedEpoch not found! Creating with a reasonable default of 0. This should only happen when you are upgrading your installation
2020-11-11 06:32:00,349 [myid:1] - INFO  [Thread-1:QuorumCnxManager$Listener@486] - My election bind port: 0.0.0.0/0.0.0.0:3888
2020-11-11 06:32:00,358 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:QuorumPeer@670] - LOOKING
2020-11-11 06:32:00,360 [myid:1] - INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:FastLeaderElection@740] - New election. My id =  1, proposed zxid=0x0
2020-11-11 06:32:00,363 [myid:1] - INFO  [WorkerReceiver[myid=1]:FastLeaderElection@542] - Notification: 1 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LOOKING (n.state), 1 (n.sid), 0x0 (n.peerEPoch), LOOKING (my state)
2020-11-11 06:32:00,368 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumCnxManager@368] - Cannot open channel to 2 at election address arcus-zk-1.arcus-zk-svc.default.svc.cluster.local:3888
java.net.UnknownHostException: arcus-zk-1.arcus-zk-svc.default.svc.cluster.local
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:354)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:327)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:393)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:365)
	at java.lang.Thread.run(Thread.java:748)
2020-11-11 06:32:00,370 [myid:1] - WARN  [WorkerSender[myid=1]:QuorumCnxManager@368] - Cannot open channel to 3 at election address arcus-zk-2.arcus-zk-svc.default.svc.cluster.local:3888
java.net.UnknownHostException: arcus-zk-2.arcus-zk-svc.default.svc.cluster.local
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:354)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:327)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:393)
	at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:365)
	at java.lang.Thread.run(Thread.java:748)
2
```

테스트 환경은 다음과 같다.

macOS mojave v10.14.5
minikube v1.14.2
docker server 19.03.13
docer client 19.03.13

**Comment by computerphilosopher** [comment]
해당 오류는 zookeeper 3.4.5 버전에서 발생하는 것으로 아직 생성되지 않은 pod의 DNS를 lookup 시도하는 것이 원인이다.

make zk 후 관련 pod를 하나씩 재실행하면 해결된다.

```
make zk
kubectl delete pods arcus-zk-0
kubectl delete pods arcus-zk-1
```

추후 arcus-3.5.8 버전이 arcus의 default 버전이 되면 자연스레 해결될 것으로 보인다
